services:
  elasticsearch:
    build: ./elasticsearch-custom
    container_name: elasticsearch
    networks:
      - internal
      
  api:
    build: ./api
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - internal

  website:
    build: ./website
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - internal

networks:
  internal:
    driver: bridge
