version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security features
      - xpack.security.transport.ssl.enabled=false  # Disable transport SSL
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./website/data:/usr/share/elasticsearch/data  # Mount the data folder into the elasticsearch container
    command: >
      bash -c "
        elasticsearch-plugin install analysis-icu &&  # Install any plugins you might need
        /usr/local/bin/docker-entrypoint.sh eswrapper &
        sleep 10 &&  # Wait for Elasticsearch to be ready
        python /usr/share/elasticsearch/data/index_programs.py  # Run your Python indexing script
      "

  jekyll:
    # Your existing jekyll service
    build: ./website
    ports:
      - "4000:4000"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
