version: '3'
services:
  website:
    build:
      context: ./website   # Adjust the build context to point to the /website folder
    ports:
      - "8080:8080"         # Expose port 8080 for the website
    depends_on:
      - elasticsearch       # Ensure Elasticsearch starts before the website

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security features
      - xpack.security.transport.ssl.enabled=false  # Disable transport SSL
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    image: python:3.9
    volumes:
      - ./website/data:/app/data
      - ./scripts:/app/scripts  # Assuming your Python script is in the scripts folder
    working_dir: /app/scripts
    depends_on:
      elasticsearch:
        condition: service_healthy  
    command: ["python", "index_programs.py"]

volumes:
  esdata:
    driver: local
