#
name: Create Docker images and publish to Github Packages

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['test-release', 'stag-release', 'prod-release', 'devops-for-launch']

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - context: ./indexer
            image_tag: indexer
          - context: ./api
            image_tag: api
          - context: ./website
            image_tag: website
    steps:
      -
        name: Lowercase Github repository
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}-${{ matrix.image_tag }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true