name: Build Docker images

on:
  push:
    branches: ['release', 'ogpds-834-search-page-updates']

jobs:
  build-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images with Docker Compose
        run: |
          docker compose build