#
name: Create Docker images and publish to Github Packages

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['test-release', 'stag-release', 'prod-release']

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./elasticsearch
            image_tag: elasticsearch
          - context: ./api
            image: api
          - context: ./website
            image: website
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}:latest
