#
name: Create Docker images and publish to Github Packages

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['test-release', 'stag-release', 'prod-release', 'wip-language-edits']

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - context: ./elasticsearch-custom
            image_tag: elasticsearch
          - context: ./api
            image_tag: api
          - context: ./website
            image_tag: website
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          tags: ghcr.io/william-yu1/federal-program-inventory:$${{ github.ref }}-{{matrix.image_tag}}
          labels: ${{ steps.meta.outputs.labels }}
          push: true