#
name: Create Docker images and publish to Github Packages

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['test-release', 'stag-release', 'prod-release', 'wip-language-edits']

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: elasticsearch-custom/Dockerfile
            image_tag: elasticsearch
          - dockerfile: api/Dockerfile
            image_tag: api
          - dockerfile: website/Dockerfile
            image_tag: website
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image_tag }}:latest
